services:
  db:
    image: postgres:18.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=querybuilder
      - POSTGRES_USER=querybuilder
      - POSTGRES_DB=querybuilder
